// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Combination struct {
	OsmID            string
	AlkisOi          string
	OsmGeom          interface{}
	AlkisGeom        interface{}
	AlkisGeomAligned interface{}
	Status           int32
	LastUpdated      pgtype.Timestamptz
}
